In [1]:
#package import
import torch as tc
import numpy as np

# Tensor handling basic

In [34]:
x = tc.empty(3,4)#빈 행렬
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [4]:
tc.ones(3,3)#1행렬

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [5]:
tc.zeros(3,3)#0행렬

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [6]:
tc.rand(4,5)#무작위값 행렬

tensor([[0.6283, 0.5878, 0.0441, 0.0901, 0.9782],
        [0.6707, 0.3780, 0.4118, 0.4098, 0.5390],
        [0.3235, 0.4765, 0.6496, 0.9794, 0.3525],
        [0.1192, 0.9394, 0.4132, 0.9047, 0.6466]])

In [53]:
#tensor 기본 정보
x = tc.rand(3,3)
print(x.shape)#=size
print(x.dtype)
print(x.device)

torch.Size([3, 3])
torch.float32
cpu


In [39]:
tc.rand(4,5, dtype = float, device = 'cpu',requires_grad = True, pin_memory = True )
#dtype = 데이터 타입
#device = 연산장치 설정
#requires_grad = tensor 연산 기록
#pin_memory = tensor 를 고정된 메모리에 할당(cpu만 가능,cuda 확인 필요)

tensor([[0.4696, 0.0870, 0.4985, 0.1628, 0.1187],
        [0.9651, 0.8728, 0.6810, 0.8023, 0.9999],
        [0.8953, 0.8726, 0.3185, 0.3184, 0.6481],
        [0.1882, 0.1509, 0.6966, 0.2648, 0.7900]], dtype=torch.float64,
       requires_grad=True)

In [23]:
#list, numpy to tensor
l = [1, 7, 19]
r = [4,78,26]
ltt = tc.tensor(l)
rtt = tc.tensor(r)
print(ltt)
print(rtt)

tensor([ 1,  7, 19])
tensor([ 4, 78, 26])


In [9]:
#tensor size 
x.size()

torch.Size([3, 4])

In [17]:
#tensor 기본 계산
x = tc.rand(3,3)
y = tc.rand(3,3)
#덧셈
add = x.add(y)#x+y도 가능
print(add)
x.add_(y)#inplace(지양해야됨)
#곱셈(내,외적)
matmul = x.matmul(y)#x@y, x,mm(y)도 가능
print(matmul)

tensor([[0.7692, 0.2762, 1.1451],
        [0.9044, 1.1649, 1.6033],
        [1.2878, 0.5788, 0.5884]])
tensor([[1.0509, 0.8205, 0.8541],
        [1.6983, 1.5826, 1.5690],
        [1.2279, 0.9022, 1.4416]])


In [46]:
#like tensor
x = tc.rand(3,3)
print(tc.ones_like(x))
print(tc.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [45]:
#통계값
x = tc.rand(3,3)
print(x.mean())
print(x.mean(dim=0))
print(x.mean(dim=1))
print(x.median())
print(x.min())
print(x.max())
print(x.argmax())

tensor(0.3757)
tensor(0.2349)
tensor(0.7985)
tensor(2)
tensor(0.0458)


In [15]:
#index
x = tc.rand(4,5)
print(x)
print(x[1,1])#특정 행렬값
print(x[1,:])#행
print(x[:,1])#열

tensor([[0.4618, 0.5695, 0.6258, 0.2833, 0.9768],
        [0.0743, 0.2133, 0.5766, 0.7647, 0.0713],
        [0.5411, 0.3649, 0.6291, 0.9116, 0.8206],
        [0.4811, 0.6013, 0.8525, 0.1211, 0.7132]])
tensor(0.2133)
tensor([0.0743, 0.2133, 0.5766, 0.7647, 0.0713])
tensor([0.5695, 0.2133, 0.3649, 0.6013])


In [44]:
#split tensor
n = 2
x = tc.rand(8,8)
vertical = tc.vsplit(x, n)#가로로 n개 나누기(tuple out)
print(vertical)
horizen = tc.hsplit(x,n)#세로로 n개 나누기(tuple out)
print(horizen)

(tensor([[0.3176, 0.0841, 0.9905, 0.9338, 0.4412, 0.0309, 0.5076, 0.9103],
        [0.3289, 0.8081, 0.2953, 0.0682, 0.1643, 0.8262, 0.7605, 0.4567],
        [0.8145, 0.9669, 0.4576, 0.5983, 0.2903, 0.6589, 0.3705, 0.3416],
        [0.0844, 0.1220, 0.7164, 0.5099, 0.8784, 0.1001, 0.1086, 0.7606]]), tensor([[6.2769e-01, 5.3192e-01, 9.8283e-01, 1.1112e-01, 6.6608e-04, 4.7008e-01,
         8.4551e-01, 9.0856e-01],
        [7.0677e-01, 1.1204e-02, 6.5102e-01, 2.5718e-01, 2.3871e-01, 9.4390e-01,
         6.2062e-01, 6.4792e-01],
        [7.6355e-01, 3.4647e-01, 2.0853e-02, 2.2673e-01, 7.8721e-02, 6.2417e-01,
         1.1474e-01, 7.5070e-01],
        [9.3067e-01, 5.8264e-02, 4.1409e-01, 8.6535e-01, 9.5883e-01, 3.3947e-01,
         5.5047e-01, 1.9287e-01]]))
(tensor([[0.3176, 0.0841, 0.9905, 0.9338],
        [0.3289, 0.8081, 0.2953, 0.0682],
        [0.8145, 0.9669, 0.4576, 0.5983],
        [0.0844, 0.1220, 0.7164, 0.5099],
        [0.6277, 0.5319, 0.9828, 0.1111],
        [0.7068, 0.0112, 0.6

In [26]:
#tensor to scalar
x = tc.rand(1)
x.item()#수의 형태만 가능

0.14443421363830566

# View function 

In [24]:
#size handling
x = tc.rand(8,8)
print(x.size())
n = x.view(4,16)
print(n.size())
e = x.view(-1,16)#-1(자동값)은 차원중 한값만 가능
print(e.size())

torch.Size([8, 8])
torch.Size([4, 16])
torch.Size([4, 16])


In [ ]:
#flatten
x.view(64)

# Matrix operate

In [60]:
#transpose matrix
x = tc.rand(3,3)
#in 1-D
print(x)
print(x.t())
# over 1-D
print(x.transpose(0,1))#recommand

tensor([[0.8910, 0.2872, 0.7498],
        [0.9329, 0.5392, 0.6190],
        [0.7624, 0.5187, 0.3699]])
tensor([[0.8910, 0.9329, 0.7624],
        [0.2872, 0.5392, 0.5187],
        [0.7498, 0.6190, 0.3699]])
tensor([[0.8910, 0.9329, 0.7624],
        [0.2872, 0.5392, 0.5187],
        [0.7498, 0.6190, 0.3699]])


In [63]:
#inverse matrix
y = tc.inverse(x)
print(y)

tensor([[  7.0044, -16.2817,  13.0475],
        [ -7.3070,  13.9433,  -8.5211],
        [ -4.1909,  14.0070, -12.2406]])
